version: "3.9"

services:
  pokemon-gym-tracker:
    image: pokemon-gym-tracker
    container_name: pokemon-gym-tracker
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL:-file:/app/data/db.sqlite}
    volumes:
      - pokemonGymTrackerData:/app/data
    restart: unless-stopped
volumes:
  pokemonGymTrackerData:

