version: "3.9"

services:
  app:
    image: pokemon-gym-tracker
    container_name: pokemon-gym-tracker
    hostname: pokemon-gym-tracker
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: "${DATABASE_URL}"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped
